;;; version-checker.lisp - Check for JavaScript library updates
;;;
;;; SPDX-License-Identifier: MIT
;;;
;;; Copyright (C) 2025  Anthony Green <green@moxielogic.com>
;;;
;;; This tool checks npm for newer versions of JavaScript libraries
;;; used by ICL and can optionally create GitHub issues for updates.

(in-package :icl-version-checker)

(defparameter *npm-registry-url* "https://registry.npmjs.org/"
  "Base URL for npm registry API.")

(defparameter *github-repo* "atgreen/icl"
  "GitHub repository for issue creation.")

(defun parse-version (version-string)
  "Parse a semver version string into a list of integers.
Returns (major minor patch) or NIL if parsing fails."
  (when (and version-string (stringp version-string))
    (let ((parts (split-sequence:split-sequence #\. (string-left-trim "v^~" version-string))))
      (handler-case
          (mapcar (lambda (p)
                    (parse-integer (string-trim '(#\Space) p) :junk-allowed t))
                  (subseq parts 0 (min 3 (length parts))))
        (error () nil)))))

(defun version< (v1 v2)
  "Return T if version V1 is less than V2."
  (let ((p1 (parse-version v1))
        (p2 (parse-version v2)))
    (when (and p1 p2)
      (loop for a in p1
            for b in p2
            do (cond ((< a b) (return t))
                     ((> a b) (return nil)))
            finally (return (< (length p1) (length p2)))))))

(defun fetch-npm-latest-version (package-name)
  "Fetch the latest version of PACKAGE-NAME from npm registry.
Returns the version string or NIL on error."
  (handler-case
      (let* ((url (concatenate 'string *npm-registry-url* package-name "/latest"))
             (response (dex:get url :headers '(("Accept" . "application/json")))))
        (let ((json (yason:parse response)))
          (gethash "version" json)))
    (error (e)
      (format *error-output* "~&Warning: Failed to fetch ~A: ~A~%" package-name e)
      nil)))

(defun check-library-updates (&key (verbose t))
  "Check all tracked libraries for updates.
Returns a list of plists for libraries with available updates."
  (let ((updates nil))
    (dolist (lib *tracked-libraries*)
      (let* ((name (getf lib :name))
             (current (getf lib :current-version))
             (npm-pkg (getf lib :npm-package)))
        ;; Skip libraries not on npm
        (if (null npm-pkg)
            (when verbose
              (format t "~&Skipping ~A (not on npm)~%" name))
            (let ((latest (fetch-npm-latest-version npm-pkg)))
              (when verbose
                (format t "~&Checking ~A (~A): current=~A, latest=~A~%"
                        name npm-pkg current (or latest "unknown")))
              (when (and latest (version< current latest))
                (push (list :name name
                            :npm-package npm-pkg
                            :current-version current
                            :latest-version latest
                            :notes (getf lib :notes))
                      updates))))))
    (nreverse updates)))

(defun format-update-report (updates)
  "Format a human-readable report of available updates."
  (if (null updates)
      "All JavaScript libraries are up to date!"
      (with-output-to-string (s)
        (format s "~&## JavaScript Library Updates Available~%~%")
        (format s "| Library | Current | Latest | Notes |~%")
        (format s "|---------|---------|--------|-------|~%")
        (dolist (u updates)
          (format s "| ~A | ~A | ~A | ~A |~%"
                  (getf u :name)
                  (getf u :current-version)
                  (getf u :latest-version)
                  (or (getf u :notes) ""))))))

(defun check-existing-issue-p ()
  "Check if there's already an open issue for dependency updates.
Returns T if an issue exists."
  (handler-case
      (let ((output (with-output-to-string (s)
                      (uiop:run-program
                       (list "gh" "issue" "list"
                             "--repo" *github-repo*
                             "--label" "dependencies"
                             "--state" "open"
                             "--json" "number")
                       :output s
                       :error-output *error-output*))))
        (let ((issues (yason:parse output)))
          (and issues (> (length issues) 0))))
    (error () nil)))

(defun create-github-issue (updates)
  "Create a GitHub issue for the available updates."
  (when (check-existing-issue-p)
    (format t "~&An open dependency update issue already exists. Skipping issue creation.~%")
    (return-from create-github-issue nil))
  (let* ((title "JavaScript dependency updates available")
         (body (format nil "~A~%~%---~%*This issue was automatically generated by the version checker.*"
                       (format-update-report updates))))
    (handler-case
        (progn
          (uiop:run-program
           (list "gh" "issue" "create"
                 "--repo" *github-repo*
                 "--title" title
                 "--body" body
                 "--label" "dependencies")
           :output *standard-output*
           :error-output *error-output*)
          (format t "~&GitHub issue created successfully.~%")
          t)
      (error (e)
        (format *error-output* "~&Failed to create GitHub issue: ~A~%" e)
        nil))))

(defun main ()
  "Main entry point for version checker.
Checks for updates and optionally creates a GitHub issue."
  (let* ((create-issue-p (member "--create-issue" (uiop:command-line-arguments) :test #'string=))
         (quiet-p (member "--quiet" (uiop:command-line-arguments) :test #'string=))
         (help-p (or (member "--help" (uiop:command-line-arguments) :test #'string=)
                     (member "-h" (uiop:command-line-arguments) :test #'string=))))
    (when help-p
      (format t "~&Usage: version-checker [OPTIONS]~%~%")
      (format t "Options:~%")
      (format t "  --create-issue  Create a GitHub issue if updates are found~%")
      (format t "  --quiet         Suppress progress output~%")
      (format t "  --help, -h      Show this help message~%")
      (uiop:quit 0))

    (format t "~&ICL JavaScript Library Version Checker~%")
    (format t "~&======================================~%~%")

    (let ((updates (check-library-updates :verbose (not quiet-p))))
      (format t "~%~A~%" (format-update-report updates))

      (cond
        ((null updates)
         (format t "~&No updates needed.~%")
         (uiop:quit 0))
        (create-issue-p
         (if (create-github-issue updates)
             (uiop:quit 0)
             (uiop:quit 1)))
        (t
         ;; Exit with code 1 if updates are available (for CI)
         (uiop:quit 1))))))
